# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: lint Dockerfile using hadolint docker image image
          command: docker run --rm -i hadolint/hadolint < Dockerfile
  build-app-karsajobs-ui:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image dengan nama ghcr.io/<username>/karsajobs:latest 
          command: docker build -t ghcr.io/egi-190137/karsajobs-ui:latest .
      - run:
          name: login pada github container registry dengan token yang tersimpan pada environment variable
          command: echo "$GH_TOKEN" | docker login ghcr.io -u egi-190137 --password-stdin
      - run:
          name: Push image ke github container registry
          command: docker push ghcr.io/egi-190137/karsajobs-ui:latest

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui
